package com.kyc.ondato.ondato_flutter

import android.content.Context
import android.util.Log
import androidx.annotation.NonNull
import com.ondato.sdk.Ondato
import com.ondato.sdk.OndatoConfig
import com.ondato.sdk.OndatoError
import com.ondato.sdk.enums.Language

import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result

/** OndatoFlutterPlugin */
class OndatoFlutterPlugin: FlutterPlugin, MethodCallHandler {
  /// The MethodChannel that will the communication between Flutter and native Android
  ///
  /// This local reference serves to register the plugin with the Flutter Engine and unregister it
  /// when the Flutter Engine is detached from the Activity
  private lateinit var channel : MethodChannel
  private lateinit var mContext: Context

  override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
    channel = MethodChannel(flutterPluginBinding.binaryMessenger, "ondato_flutter")
    channel.setMethodCallHandler(this)
    mContext = flutterPluginBinding.applicationContext
  }

  override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
    val args = call.arguments;
        when (call.method) {
            "getPlatformVersion" ->
                result.success("Android ${android.os.Build.VERSION.RELEASE}")
            "initialSetup" -> initialSetup(result, args)
            "startIdentification" -> startIdentification(result)
            else -> result.notImplemented()
        }
  }

  override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
    channel.setMethodCallHandler(null)
  }

  private fun startIdentification(result: Result) {
      try {
          Ondato.startIdentification(mContext, object : Ondato.ResultListener {
              override fun onSuccess(identificationId: String?) {
                  result.success(mapOf("identificationId" to identificationId))
              }

              override fun onFailure(identificationId: String?, error: OndatoError) {
                 val message = error.message;
                 Log.d("ONDATO PLUGIN", "ERROR FULL $error")
                 Log.d("ONDATO PLUGIN", "ERROR MESSAGE $message")
                   result.success(
                       mapOf(
                           "identificationId" to identificationId,
                           "error" to error.message.toString()
                       )
                   )
              }
          })
      } catch (e: Exception) {
          result.error(" ", e.message, e.stackTrace.toString())
      }
  }

  private fun initialSetup(result: Result, args: Any) {
    val map = args as? HashMap<String, Any>
    if (map != null) {
        val mode = map["mode"] as String
        val identificationId = map["identificationId"] as String
        val flowConfig = map["flowConfiguration"] as? HashMap<String, Boolean>
        val language = map["language"] as String
        val jsonConfiguration = map["jsonConfiguration"] as? String

        Log.d("ONDATO PLUGIN", "identificationID $identificationId")

        val config = OndatoConfig.Builder()
            .setIdentityVerificationId(identificationId) //should by generated by user and passed here
            .setMode(getMode(mode)) //default is TEST
            .setLanguage(getLanguage(language))

        if (jsonConfiguration?.isNotEmpty() == true) {
            config.setConfiguration(jsonConfiguration)
        }
        
        Ondato.init(config.build())
        result.success(true)
    } else {
        result.error("", "", "Missing parameters")
    }
  }

  private fun getLanguage(str: String?): Language {
    var lang = Language.English
    when (str) {
        "en" -> lang = Language.English
        "lt" -> lang = Language.Lithuanian
        "sq" -> lang = Language.Albanian
        "bg" -> lang = Language.Bulgarian
        "ca" -> lang = Language.Catalan
        "cs" -> lang = Language.Czech
        "nl" -> lang = Language.Dutch
        "et" -> lang = Language.Estonian
        "fi" -> lang = Language.Finnish
        "fr" -> lang = Language.French
        "de" -> lang = Language.German
        "el" -> lang = Language.Greek
        "hu" -> lang = Language.Hungarian
        "it" -> lang = Language.Italian
        "lv" -> lang = Language.Latvian
        "pl" -> lang = Language.Polish
        "pt" -> lang = Language.Portuguese
        "ro" -> lang = Language.Romanian
        "ru" -> lang = Language.Russian
        "es" -> lang = Language.Spanish
        "sv" -> lang = Language.Swedish
        "uk" -> lang = Language.Ukrainian
        "vi" -> lang = Language.Vietnamese
    }
    return lang
  }

  private fun getMode(str: String?): OndatoConfig.Mode {
      var mode = OndatoConfig.Mode.TEST
      when (str) {
          "live" -> mode = OndatoConfig.Mode.LIVE
          "test" -> mode = OndatoConfig.Mode.TEST
      }
      return mode
  }

}
