buildscript {
    ext.kotlin_version = '2.2.20'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id("com.android.library")
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://raw.githubusercontent.com/ondato/ondato-sdk-android/main/repos/" }
        maven { url 'https://jitpack.io' }
        mavenLocal()
    }
    configurations.all {
        resolutionStrategy {
            force("androidx.appcompat:appcompat:1.6.1")
            force("androidx.appcompat:appcompat-resources:1.6.1")
            force("androidx.lifecycle:lifecycle-livedata-core:2.7.0")
            force("androidx.profileinstaller:profileinstaller:1.3.1")
            force("com.airbnb.android:lottie:6.6.6")
            force("org.slf4j:slf4j-api:2.0.0")
        }
    }
}

android {
    compileSdkVersion 37
    namespace = 'com.kyc.ondato.ondato_flutter'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 26
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.kyc.ondato:sdk-core:3.6.0"
    implementation 'androidx.annotation:annotation:1.2.0'
}

